In [10]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [11]:
dataset = pd.read_csv('Churn_Modelling.csv')
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [12]:
x = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [13]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [24]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
label_encoder = LabelEncoder()
x[:, 2] = label_encoder.fit_transform(x[:, 2])
x[:, 2]

array([1115, 1177, 2040, ..., 1570, 2345, 2751], dtype=object)

In [32]:
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([('ohe', OneHotEncoder(), [1])], remainder='passthrough')
x = np.array(ct.fit_transform(x), dtype= np.str_)
x = x[:, 1:]
x

array([['0.0', '0.0', '619', ..., '1', '1', '101348.88'],
       ['0.0', '1.0', '608', ..., '0', '1', '112542.58'],
       ['0.0', '0.0', '502', ..., '1', '0', '113931.57'],
       ...,
       ['0.0', '0.0', '709', ..., '0', '1', '42085.58'],
       ['1.0', '0.0', '772', ..., '1', '0', '92888.52'],
       ['0.0', '0.0', '792', ..., '1', '0', '38190.78']], dtype='<U32')

In [33]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size= 0.2, random_state= 0)

In [35]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)
x_train

array([[-0.5698444 ,  1.74309049,  0.16958176, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [ 1.75486502, -0.57369368, -2.30455945, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [-0.5698444 , -0.57369368, -1.19119591, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [-0.5698444 , -0.57369368,  0.9015152 , ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-0.5698444 ,  1.74309049, -0.62420521, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [ 1.75486502, -0.57369368, -0.28401079, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [36]:
#Building Artificial Neural Network
from tensorflow.keras.models import Sequential
from keras.layers import Dense

classifier = Sequential()

In [37]:
#Adding the input and the first hidden Layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

In [38]:
#Adding the next Hidden Layer
classifier.add(Dense(units = 6, kernel_initializer= 'uniform', activation = 'relu'))

In [39]:
#Adding the output Layer
classifier.add(Dense(units = 1, kernel_initializer= 'uniform', activation = 'sigmoid'))

In [40]:
#cCompile the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [42]:
#Fit the ANN model to the training Set
classifier.fit(x_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
800/800 [==============================] - 3s 2ms/step - loss: 0.4876 - accuracy: 0.7960
Epoch 2/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4338 - accuracy: 0.7960
Epoch 3/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4284 - accuracy: 0.7960
Epoch 4/100
800/800 [==============================] - 2s 3ms/step - loss: 0.4246 - accuracy: 0.8126
Epoch 5/100
800/800 [==============================] - 3s 3ms/step - loss: 0.4220 - accuracy: 0.8214
Epoch 6/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4203 - accuracy: 0.8271
Epoch 7/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4183 - accuracy: 0.8281
Epoch 8/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4169 - accuracy: 0.8314
Epoch 9/100
800/800 [==============================] - 2s 3ms/step - loss: 0.4160 - accuracy: 0.8331
Epoch 10/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4149 - accura

800/800 [==============================] - 2s 2ms/step - loss: 0.4017 - accuracy: 0.8366
Epoch 82/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4016 - accuracy: 0.8356
Epoch 83/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4012 - accuracy: 0.8363
Epoch 84/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4008 - accuracy: 0.8363
Epoch 85/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4014 - accuracy: 0.8364
Epoch 86/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4014 - accuracy: 0.8384
Epoch 87/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4011 - accuracy: 0.8374
Epoch 88/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4009 - accuracy: 0.8365
Epoch 89/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4010 - accuracy: 0.8366
Epoch 90/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4004 - accuracy: 

In [43]:
y_pred = classifier.predict(x_test)
y_pred = (y_pred > 0.5)

63/63 [==============================] - 0s 2ms/step


In [44]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [45]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1544   51]
 [ 257  148]]


0.846